/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus')['ElAlert']
    ElAside: typeof import('element-plus')['ElAside']
    ElBadge: typeof import('element-plus')['ElBadge']
    ElButton: typeof import('element-plus')['ElButton']
    ElCard: typeof import('element-plus')['ElCard']
    ElCheckbox: typeof import('element-plus')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus')['ElCheckboxGroup']
    ElCol: typeof import('element-plus')['ElCol']
    ElConfigProvider: typeof import('element-plus')['ElConfigProvider']
    ElContainer: typeof import('element-plus')['ElContainer']
    ElDatePicker: typeof import('element-plus')['ElDatePicker']
    ElDescriptions: typeof import('element-plus')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus')['ElDialog']
    ElDivider: typeof import('element-plus')['ElDivider']
    ElDropdown: typeof import('element-plus')['ElDropdown']
    ElDropdownItem: typeof import('element-plus')['ElDropdownItem']
    ElEmpty: typeof import('element-plus')['ElEmpty']
    ElForm: typeof import('element-plus')['ElForm']
    ElFormItem: typeof import('element-plus')['ElFormItem']
    ElHeader: typeof import('element-plus')['ElHeader']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElImage: typeof import('element-plus')['ElImage']
    ElInput: typeof import('element-plus')['ElInput']
    ElInputNumber: typeof import('element-plus')['ElInputNumber']
    ElMain: typeof import('element-plus')['ElMain']
    ElMenu: typeof import('element-plus')['ElMenu']
    ElMenuItem: typeof import('element-plus')['ElMenuItem']
    ElOption: typeof import('element-plus')['ElOption']
    ElPagination: typeof import('element-plus')['ElPagination']
    ElRadio: typeof import('element-plus')['ElRadio']
    ElRadioButton: typeof import('element-plus')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus')['ElRadioGroup']
    ElRow: typeof import('element-plus')['ElRow']
    ElSelect: typeof import('element-plus')['ElSelect']
    ElSwitch: typeof import('element-plus')['ElSwitch']
    ElTable: typeof import('element-plus')['ElTable']
    ElTableColumn: typeof import('element-plus')['ElTableColumn']
    ElTabPane: typeof import('element-plus')['ElTabPane']
    ElTabs: typeof import('element-plus')['ElTabs']
    ElTag: typeof import('element-plus')['ElTag']
    ElTimeline: typeof import('element-plus')['ElTimeline']
    ElTimelineItem: typeof import('element-plus')['ElTimelineItem']
    ElUpload: typeof import('element-plus')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
